-- Script GUID: {1CA142E3-3553-46FB-A08F-3912F3DB248B}
-- Decompiled with the Synapse X Luau decompiler.

return {
    "Hope you enjoy playing Phantom Forces!",
    "More helpful messages from me will come in the future.",
    "Please get parental permission before going to battle.",
    "You can turn on and off different UI elements (like the chat) in the settings menu.",
    "Pressing H will allow you to admire your gun.",
    "You can initiate a votekick on players that are cheating or violating the ROBLOX ToS. you can type `/votekick` for more info.",
    "You can report players for cheating using the report command if you have evidence. You can type /report for more info.",
    "Be mindful of what you say in chat - You can be reported for misuse, toxicity, or bypassing the Roblox filter.",
    "Weapon rank does not determine usefulness.",
    "Adjust your mouse setting to fit your style.",
    "Slides can be in multiple directions, not just forward.",
    "Take a break if you need it. Keep your head on your shoulders.",
    "You can dolphin dive in mid-air. Use it to traverse maps.",
    "You're always winning, even if you lose.",
    "Variety is the spice of life. Use a different gun every day.",
    "Selling skins will give you credits.",
    "Make sure your music isn't drowning out the game.",
    "Did you know that Phantom Forces has a test place? Check it out for content in the works.",
    "Be sure to check your settings in the Roblox menu and in the game if you're having performance issues.",
    "Your Field of Vision, HUD elements and graphical details can all be tweaked in the settings.",
    "Press TAB to open the leaderboard. Useful information can be viewed from here, such as player names, their KDR, and your own ping.",
    "Some melees are hidden until you unlock them. Try rolling skin cases to find them!",
    "You have a higher chance to unlock higher tiered skins the more you open a case.",
    "Be sure to check out SCL, our competitive league!",
    {"Helmets will not block bullets.", "You aren't safe."},
    "Grenades have a fuse time of 5 seconds. Use this to your advantage.",
    "You can cook a grenade by holding down G. Just make sure to let go before it blows up.",
    "Grenades bounce and slide across walls and floors. Perfect for pushing around corners.",
    "The explosion radius of a grenade is 30 studs, but loses potency to down a full health enemy well before that",
    "The ticking heard from the frag grenade is not actually real, it is your body warning of danger.",
    "Be vigilant for grenades being dropped when the user perishes, they will explode.",
    "A flash hider will hide the flash from your gun firing, but will reduce hipfire stability when firing.",
    "Suppressors can hide your position on the minimap, to a point. Different suppressors have different reveal ranges.",
    "Suppressors reduce damage at range and bullet velocity, but often will help with hipfire accuracy.",
    "Compensators and muzzle brakes change how your gun handles. Compensators reduce sideways recoil, muzzle brakes reduce vertical recoil.",
    "If you attach a canted sight on your gun, press T to switch to and from it.",
    "If you don't have canted sights on your shotgun, press T to switch to and from an over-the-shoulder aiming point.",
    "Lasers are a powerful tool to assist with aiming.",
    "Lasers affect your stats in different ways.",
    "Each grip serves a different purpose on a gun. Experiment with them to see which one works best.",
    "There's not a single grip that works the best for every weapon. Experiment to find which works best.",
    "Vertical / Chainsaw / Romanian grips are excellent for hipfire, but reduces your aimfire accuracy.",
    "The ergonomic Skeleton grip is exceptional for weapons that could use more aimspeed, but worse for those who deal with recoil constantly.",
    "Can't decide between a laser or a grip? The Hera CQR grip combines both a laser and a grip into one package, but aims the slowest.",
    "Potato grip combines a retooled angled grip with the usefulness of a flashlight. Not suitable for consumption.",
    "Attachments can drastically change the performance of your firearm",
    "Some attachments change the name of your gun.",
    "Tracerless ammo is hard to see, but not invisible.",
    "Attachment cost does not determine usefulness.",
    "Some guns have unique attachments. Try them out!",
    "Low zoom optics do not reduce recoil. You just see less, it's still there.",
    "Getting 5,000 kills with a sniper rewards you with the ability to attach all other sniper scopes on that gun.",
    "Grips do affect breath mechanics.",
    "Use the optic you prefer, not the one you're told to use.",
    "Attachments such as the MARS optic also benefit from stat changes due to the visible laser!",
    "Staying on the hill in King of the Hill will drain the enemy team's points faster.",
    "Capturing objectives gives you a lot of experience points.",
    "You can nullify enemy capture progress by standing on the objective, contesting it.",
    "Protect your flag in CTF, but also make sure to engage the enemy for their flag.",
    "Capture an enemy flag to gain a huge amount of points.",
    "Know when it's safe to grab the tag in Kill Confirmed.",
    "KDR is not everything. Remember to play the objective.",
    "Capturing positions gives you more points than getting kills.",
    "See your enemy camping the objective? Maybe tossing a grenade will flush them out.",
    "Objectives cannot be captured if the enemy is on them.",
    "Burst fire on weapons can be interrupted early by releasing the mouse button (depending on the gun).",
    "When using an automatic weapon at range, it is often more effective to fire a few controlled bullets (tap fire) instead of spraying.",
    "The longer the range, the less damage bullets will deal.",
    "Most guns can reload an extra round after a full magazine because a round is loaded into the chamber.",
    "In most magazine fed guns, reloading on an empty magazine will take longer than reloading halfway.",
    "Switching to your secondary is oftentimes faster than reloading.",
    "Your firearm can be replaced with dropped weapons on the ground.",
    "High caliber guns such as LMGs and sniper rifles can penetrate through thin walls.",
    "Pressing V can switch firemodes for certain automatic guns.",
    "Holding SHIFT while aiming with a scope will steady it from swaying.",
    "Bullets do have drop. Compensate for this by aiming higher than your target at farther ranges.",
    "Knives will only one hit kill when stabbing a player from behind.",
    "Aiming down sights of a shotgun will not tighten the spread, but does center your aim.",
    "Try to lead your shot if your target is moving, otherwise you'll miss your target.",
    "Heavy melees like the Zweihander and World Buster require you hold down the melee button.",
    "Before going to combat, check the stats of your weapons.",
    "Generally melee weapons are faster than firearms. There are exceptions.",
    "Relying on a single type of weapon is boring, but also exposes your weaknesses.",
    "PDWs are great at rushing objectives with high fire rates and hip accuracy allow for more agressive playstyle.",
    "Most Sniper Rifles will kill with a single headshot at all distances.",
    "Hipfiring can be more effective than aiming in at close range.",
    "Staying still is a quick way to eat more bullets. Movement is not only for traversal but for combat.",
    "Snipers, while valued for their one shot potential, are also powerful for ensuring targets shot in the chest or limbs at range will most likely die in the next gunfight they get into.",
    "Shotguns are truly in their element in tight spaces and around choke points. Use them effectively to punish enemies who rush carelessly into close range gunfights.",
    "Avoid staying in a spot for too long after killing someone, or they will find you again.",
    "Make sure your teammate is in a safe position before spawning on them.",
    "Press E to spot enemy players that are in view. This marks them with a red diamond, and lights them up on your radar.",
    "Your radar can be your best tool for seeing around you. Any enemy that is shooting will be shown with a red dot.",
    "Look for paths around the enemy, then come up beside or behind them - this is known as flanking.",
    "Pay attention to sounds. You can locate enemies quickly even if they're not spotted just by the sound of their gun.",
    "Listen to the sounds of footsteps, as they tell you what someone is walking on, and where they are.",
    "The footsteps of your teammates are much quieter than the enemy footsteps.",
    "Learn what sounds a player makes when they move over surfaces (like metal, grass and concrete) to further narrow down where your enemy is.",
    "Sometimes it is better to lure an enemy into a situation where you have an advantage instead of rushing out.",
    "The highest spots on maps, as well as wide open spaces, are often the most dangerous to be in.",
    "Communicate with only your team by prefixing your message with %. For example: %Hello!",
    "If you're spotted seek cover. Someone is watching you.",
    "Sometimes your team can gain an advantage over an enemy by suppressing their position and flanking the enemy.",
    "Read the description of the attachments and weapons, they're there for a reason.",
    "Be mindful of what map you're going into. Choose a weapon best suited for it.",
    "You can change the color of your reticle once you get 200 kills with the sight.",
    "Camping is a legitimate tactic. Flank or throw grenades at people staying in one spot.",
    "Ever wonder where you get such wonderful lead-spitting toys? The Broker is the man who handles the funding and armament of every soldier.",
    "Phantoms and Ghosts were once a unified group until a falling out caused them to split. The name for the group has been lost to time.",
    "Mercenaries constantly shift sides depending on who is paying more.",
    "Phantoms originate from America. Ghosts come from Egypt.",
    "The two main mercenary groups may cause untold amounts of damage, but at least they hire without discrimination!",
    "Desert Storm is an arid town set within one of the deserts of Egypt. It is one of the bases of the Ghost mercenary group.",
    "Phantoms and Ghosts aren't the only large mercenary groups out there...",
    "It's not your gun if you're dead.",
    "Did you forget to reload?",
    "Bee Bee Boo Boo.",
    "Stop, hammer time!",
    "Behind you.",
    "( \205\161\194\176 \205\156\202\150 \205\161\194\176)",
    "\194\175_(\227\131\132)_/\194\175"
}
