local a=game.ReplicatedStorage.ChrModels["Red Panda"]:Clone()
a.Parent=game.ReplicatedStorage.ChrModels
a.Name="Ku Klux Klan"
for _,v in pairs(a:GetChildren())do
    if v:IsA("Accessory")or v:IsA("Shirt")or v:IsA("Pants")or tostring(v)=="Female"then
        v:Destroy()
    end
end
a.Head.face:Destroy()
a["Body Colors"].HeadColor3=Color3.new(1,1,1)
a["Body Colors"].LeftArmColor3=Color3.new(1,1,1)
a["Body Colors"].RightArmColor3=Color3.new(1,1,1)
a["Body Colors"].LeftLegColor3=Color3.new(1,1,1)
a["Body Colors"].RightLegColor3=Color3.new(1,1,1)
a["Body Colors"].TorsoColor3=Color3.new(1,1,1)
a.Head.Mesh.MeshId="rbxassetid://4642578374"
a.Head.Mesh.Offset=Vector3.new(0,.75,0)
a.Head.Mesh.OriginalSize:Destroy()
a.Head.Mesh.Scale=Vector3.new(.75,1.25,.75)
local b=Instance.new("StringValue")
b.Value="Flamming Pumpkin"
b.Name="Ku Klux Klan"
b.Parent=game.ReplicatedStorage.FavoriteWeapons
local c=Instance.new("Part")
c.Parent=a
c.Name="Right Eye"
c.Size=Vector3.new(.075,.25,25)
c.Color=Color3.new()
c.Material="SmoothPlastic"
c.CFrame=a.Head.CFrame
c.Shape="Cylinder"
local d=Instance.new("Weld")
d.Parent=c
d.Part0=c
d.Part1=a.Head
d.C1=CFrame.new(.2,.25,-.5)*CFrame.Angles(0,math.rad(90),0)
local e=Instance.new("Part")
e.Parent=a
e.Name="Left Eye"
e.Size=Vector3.new(.075,.25,25)
e.Color=Color3.new()
e.Material="SmoothPlastic"
e.CFrame=a.Head.CFrame
e.Shape="Cylinder"
local f=Instance.new("Weld")
f.Parent=e
f.Part0=e
f.Part1=a.Head
f.C1=CFrame.new(-.2,.25,-.5)*CFrame.Angles(0,math.rad(90),0)
local g=Instance.new("Part")
g.Parent=a
g.Name="Red Stuff"
g.Size=Vector3.new(.1,.5,.5)
g.Color=Color3.new(1,0,0)
g.Material="SmoothPlastic"
g.CFrame=a.UpperTorso.CFrame
g.Shape="Cylinder"
local h=Instance.new("Weld")
h.Parent=g
h.Part0=g
h.Part1=a.UpperTorso
h.C1=CFrame.new(-.5,.25,-.5)*CFrame.Angles(0,math.rad(90),0)
local i=Instance.new("Part")
i.Parent=g
i.Size=Vector3.new(.11,.1,.45)
i.Color=Color3.new(1,1,1)
i.Material="SmoothPlastic"
i.CFrame=a.UpperTorso.CFrame
local j=Instance.new("Weld")
j.Parent=i
j.Part0=i
j.Part1=g
local k=Instance.new("Part")
k.Parent=g
k.Size=Vector3.new(.11,.45,.1)
k.Color=Color3.new(1,1,1)
k.Material="SmoothPlastic"
k.CFrame=a.UpperTorso.CFrame
local l=Instance.new("Weld")
l.Parent=k
l.Part0=k
l.Part1=g
local m=Instance.new("Part")
m.Parent=g
m.Size=Vector3.new(.12,.15,.15)
m.Color=Color3.new()
m.Material="SmoothPlastic"
m.CFrame=a.UpperTorso.CFrame
local n=Instance.new("Weld")
n.Parent=m
n.Part0=m
n.Part1=g
n.C1=CFrame.new()*CFrame.Angles(math.rad(45),0,0)
local o=Instance.new("Part")
o.Parent=g
o.Size=Vector3.new(.13,.1,.1)
o.Color=Color3.new(1,1,1)
o.Material="SmoothPlastic"
o.CFrame=a.UpperTorso.CFrame
local p=Instance.new("Weld")
p.Parent=o
p.Part0=o
p.Part1=g
p.C1=CFrame.new()*CFrame.Angles(math.rad(45),0,0)
